stages:
  - build
  - deploy

build-check:
  image: emergent:bionic
  stage: build
  only:
    - master
  script:
    - premake5 gmake
    - make -j4

windows-check:
  image: emergent:windows
  stage: build
  only:
    - master
  script:
    - premake5 --os=windows gmake
    - make CXX=x86_64-w64-mingw32-g++ -j4

# Header-only library so package is the same for each distribution
package-all:
  image: emergent:bionic
  stage: build
  only:
    - tags
  script:
    - cd packages
    - ./build
    - mkdir -p /packages/xenial/oss/
    - mkdir -p /packages/bionic/oss/
    - mkdir -p /packages/focal/oss/
    - cp libentity-dev_*.deb /packages/xenial/oss/libentity-dev.deb
    - cp libentity-dev_*.deb /packages/bionic/oss/libentity-dev.deb
    - cp libentity-dev_*.deb /packages/focal/oss/libentity-dev.deb
  artifacts:
    paths:
      - packages/*.deb

deploy-packages:
  image: emergent:deploy
  stage: deploy
  when: on_success
  only:
    - tags
  dependencies:
    - package-all
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - cd packages
    - scp *.deb gitlab@downloads.emergent-design.co.uk:/srv/downloads/libentity/
