include:
  - project: 'core/common'
    file: '/templates/ci.yml'

variables:
  COMPONENT: oss

# Header-only library so package is the same for each distribution
package-entity:
  extends: [ .build-packages ]
  variables: { MODULE: entity, MATCH: /^v.*$/ }

deploy-entity:
  needs: [ package-entity ]
  extends: [ .deploy-simple ]
  variables: { MATCH: /^v.*$/ }
