stages:
  - build
  - deploy

build-check:
  stage: build
  only: [ master ]
  script:
    - earthly +build

# Header-only library so package is the same for each distribution
package-all:
  stage: build
  only: [ tags ]
  script:
    - earthly +package
  artifacts:
    paths:
      - build/**.deb

deploy-packages:
  stage: deploy
  when: on_success
  only: [ tags ]
  dependencies: [ package-all ]
  script:
    - for REPO in bionic focal jammy; do
        phi-deploy build/libentity-dev_*.deb $REPO oss;
      done
